### ISSUE TITLE
Parallel testing affects code coverage results

### ISSUE THREAD

**Issue by dabrahams** [swiftlang/swift-package-manager#7069] opened 2023-11-08 17:18 UTC
### Description

I turned on parallel testing in CI (`swift test --parallel`) and the coverage report for my release build (but not my debug build!) [fell below my minimum threshold](https://github.com/hylo-lang/hylo/actions/runs/6801347307/job/18491977088#step:5:14).  Previously [it was fine](https://github.com/hylo-lang/hylo/actions/runs/6787649783/job/18451797840#step:5:14).

**Comment by MaxDesiatov** [comment] 2023-11-08 17:53
cc @hamishknight who's currently looking into code coverage. I wonder how the current implementation known to have limitations could cause this?

**Comment by hamishknight** [comment] 2023-11-08 20:27
This sounds like it _could_ be a bug in the LLVM coverage runtime, since `--parallel` won't affect what the compiler emits. That being said, I haven't been able to reproduce this locally, although interestingly the coverage figure I get is 79%. I should note that there seems to be a little run-to-run variance (on the order of a 1/10 of a percent), even when running without `--parallel`.

FWIW I'm getting my numbers by doing:

```shell
❯ jq '[.data[].files?[] | select(.filename | contains("repro/hylo/Sources")) | .summary.lines.percent ] | add/length' .build/release/codecov/Hylo.json
79.36266938020735
```

The source files being selected here seem to more or less match what `swift-test-codecov` is matching, I've also tried selecting the exact files it's looking at and get a similar percentage.

But if I run swift-test-codecov, I get a different figure:

```shell
❯ swift run --package-path ../swift-test-codecov swift-test-codecov .build/release/codecov/Hylo.json
Building for debugging...
Build complete! (0.12s)
87.45%
```

which is interesting (but again, consistent with or without `--parallel`). If I manually take the percent figures outputted in the table provided by `swift-test-codecov` and average them myself, I get 79%, so maybe there's something going on with swift-test-codecov here, or maybe I'm overlooking something.

I've also looked at the total report with:

```shell
❯ xcrun llvm-cov report -instr-profile .build/release/codecov/default.profdata .build/release/HyloPackageTests.xctest/Contents/MacOS/HyloPackageTests
```

And that gives the same line coverage with and without `--parallel` (it's 69.24%, but that's including tests and dependencies)

**Comment by grynspan** [comment] 2024-07-18 01:10
Oh, I called it!

**Comment by grynspan** [comment] 2024-07-19 11:13
Tracked internally at Apple as rdar://131971679.

**Comment by grynspan** [comment] 2024-07-22 19:08
@dabrahams Can you give us some more info on your situation? We're having trouble reproducing the issue. Do you have a package that consistently shows the problem?

**Comment by dabrahams** [comment] 2024-07-22 20:07
I haven't looked at this in ages, but you could try forking the project and rolling back to the the states before and after [this PR](https://github.com/hylo-lang/hylo/pull/1129).

**Comment by grynspan** [comment] 2024-07-22 21:55
It looks like parallel testing is working reliably for you now—is that correct?

**Comment by dabrahams** [comment] 2024-07-25 18:06
Except on Windows where SPM build/test doesn't work for us in CI at all, yes, that appears to be correct.

**Comment by grynspan** [comment] 2024-07-25 20:23
I assume your difficulties with Windows are tracked in another GitHub issue. 🙃 If not, please do file.

Given that this works reliably for you (where you're able to check, anyway), I'm closing this issue. If it crops back up, please do reopen it.

**Closed by grynspan** 2024-07-25 20:23 UTC
Labels: bug, swift test
