### ISSUE TITLE
swift test [list] --skip-build still checkouts dependencies

### ISSUE THREAD

**Issue by tristanlabelle** [swiftlang/swift-package-manager#7113] opened 2023-11-21 13:36 UTC
### Description

`swift test list` always fetches and create working copies for git package dependencies, even if invoked with `--skip-build` and/or `--skip-update`.

This was discovered in the context of https://github.com/swift-server/vscode-swift/pull/638 . The Swift VS Code extension automatically tries to discover tests at startup by running this command, which for large projects ends up causing a long-lasting checkout operation in the background, which can then overlap with `swift build` commands and cause corrupted checkouts.

(The rationale for this bug also applies for bare `swift test`, without `list`)

### Expected behavior

`--skip-build` should also imply not resolving packages.

### Steps to reproduce

1. Create a new swift project with one git package dependency
2. Run `swift test list --skip-build` or `swift test list --skip-build --skip-update`

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.10.0-dev

### Swift & OS version (output of `swift --version ; uname -a`)

compnerd.org Swift version 5.11-dev (LLVM 3d6e0f96eb2caa2, Swift f6e8fd2f369d95d)
Target: x86_64-unknown-windows-msvc
(main branch build from 2023-11-16)

**Comment by grynspan** [comment] 2023-11-27 16:49
In order to list tests, the test target must be built and run, so the right solution may be to disallow these arguments with `swift test` and `swift test list`.

**Comment by adam-fowler** [comment] 2023-11-27 17:32
> In order to list tests, the test target must be built and run, so the right solution may be to disallow these arguments with `swift test` and `swift test list`.

That would be problematic for the VSCode extension and any other UI reliant on getting the test list using `swift test list`. Triggering a build, which could be a long process, to update a UI is not ideal.

We currently don't have a method to get the list of tests that doesn't require a build at some point but being able to use the results from previous builds helps make the UI more responsive. And if we ask to skip the build we would expect to skip the resolve that is triggered prior to that.

**Comment by grynspan** [comment] 2023-11-27 17:50
I don't have any objection to having `--skip-build` or `--skip-update` imply "don't resolve dependencies", or alternatively to adding a new `--skip-resolution` option. The issue description seems to be describing a clean package build, so forgive me if I'm confusing things—to be clear, you're concerned with *subsequent* builds only, not the initial build?

**Comment by tristanlabelle** [comment] 2023-11-27 22:21
My thinking is along @adam-fowler 's lines: it's useful to have a "readonly" query for tests for tooling purposes. Also, it's not useful that `--skip-build` will still update the dependencies if it's not going to be able to list tests anyways because it won't build afterwards.

**Comment by grynspan** [comment] 2023-11-28 13:06
I think I understand that part—where I'm a bit confused (sorry!) is what behaviour would be expected from the VSCode side on the _first_ call. Zero results returned until the first time the user builds the package? (I am not arguing for or against that, just trying to understand what the expected behaviour would be.)

**Comment by adam-fowler** [comment] 2023-11-28 13:13
Currently in VSCode if tests are unavailable it displays a message telling the user to build the package to get them. 

There is a SourceKit-LSP solution in development which will also include test locations but until then I have to rely on `swift test list`.

**Comment by grynspan** [comment] 2023-11-28 13:19
Understood. We've got an eye on that SK-LSP PR (https://github.com/apple/sourcekit-lsp/pull/978, right?) as well.

**Comment by adam-fowler** [comment] 2023-11-28 13:20
Yep that's the one

**Comment by dschaefer2** [comment] 2024-10-15 18:56
VSCode is already using sourcekit-lsp starting in 6.0. We no longer need this. If people feel strongly that the swift test list command should behave like this then please reopen. @grynspan's first comment here makes me wonder if that even works.

**Comment by dschaefer2** [comment] 2024-10-15 18:57
Closing

**Closed by dschaefer2** 2024-10-15 18:57 UTC
Labels: bug, swift test
