### ISSUE TITLE
Running pre-built tests with coverage fails with error: The folder “codecov” doesn’t exist

### ISSUE THREAD

**Issue by michalszelagsonos** [swiftlang/swift-package-manager#6498] opened 2023-04-29 12:55 UTC
### Description

I'd like to build in one step and run tests with coverage in another step.  This allows for measuring how long builds and tests take in CI.  According to this post, this used to work in 5.6: https://forums.swift.org/t/swift-5-7-build-tests-enable-code-coverage/60345.  This stopped working in 5.7 and is broken in 5.8.  The tests run but the command fails when coverage data is being created.  Error:
```
error: The folder “codecov” doesn’t exist
```

### Expected behavior

Running pre-built tests with coverage executes the tests and produces coverage artifacts.

### Actual behavior

The tests run but code coverage information fails to be produced.

### Steps to reproduce

1. swift build --build-tests
2. swift test --skip-build --enable-code-coverage

### Swift Package Manager version/commit hash

5.8

### Swift & OS version (output of `swift --version ; uname -a`)

$ swift --version
```
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```
$ uname -a
```
Darwin ***-arm 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

**Comment by luncliff** [comment] 2023-08-30 07:23
Encountered same issue in Swift 5.8.1 (Xcode 14.3.1, `14E300c`)

```console
$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
```

```console
$ uname -a
Darwin XXXXXXXXXX.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
```

**Comment by thecb4** [comment] 2023-12-18 16:31
Any news here?

**Comment by grynspan** [comment] 2024-07-24 12:48
As of Swift 6, you can now pass `--enable-code-coverage` to `swift build`. That should resolve this issue.

**Comment by grynspan** [comment] 2024-07-24 12:48
Duplicate of #7518

**Closed by grynspan** 2024-07-24 12:48 UTC
Labels: bug, swift test
