### ISSUE TITLE
[SR-14855] 'swift test --verbose' does not print compilation commands

### ISSUE THREAD

**Issue by typesanitizer** [swiftlang/swift-package-manager#4408] opened 2021-06-29 19:45 UTC
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14855      |
   |Radar             | rdar://problem/79927151         |
   |Original Reporter | @typesanitizer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 6159b6340eeb9c632aa7bd61e577fa00

  </details>

**Issue Description:**

Here is the output I get when running 'swift test --verbose' for a package.

``` java
/usr/bin/xcrun --sdk macosx --show-sdk-path
/usr/bin/xcrun --sdk macosx --show-sdk-platform-path
/Users/varun/foss-swift/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/bin/swiftc -print-target-info
/usr/bin/xcrun --sdk macosx --find xctest
/Users/varun/foss-swift/build/Ninja-RelWithDebInfoAssert/swift-macosx-x86_64/bin/swiftc -print-target-info
[0/0] Build complete!
/Applications/Xcode.app/Contents/Developer/usr/bin/xctest /Users/varun/tmp/Thespian/.build/x86_64-apple-macosx/debug/ThespianPackageTests.xctest
```

This is missing the compilation/build command itself. Perhaps the `--verbose` is not being passed down to other commands that are being invoked?

**Comment by grynspan** [comment] 2024-08-13 20:47
I am not able to reproduce this issue either. It's been a few years of course; closing, but please reopen if you're still seeing an issue!

**Closed by grynspan** 2024-08-13 20:47 UTC
Labels: bug
